name: ctsm
channels:
  - conda-forge
dependencies:
  - bokeh
  - dask
  - distributed
  - jupyter
  - jupyterlab
  - geoviews
  - matplotlib
  - netcdf4>1.4
  - numpy
  - pandas
  - xarray
  - pip:
    - click
